[CmdletBinding()]
param([string]$PsqlPath = 'psql')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProjectRoot=Split-Path -Parent $PSScriptRoot
$MigrationFileName='20260831_00_admin_readiness_durable_security_storage.sql'
$EvidenceRoot=Join-Path $ProjectRoot 'local-evidence/admin-readiness-security'
$PostgresEnvironmentNames=@('PGHOST','PGHOSTADDR','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS','PGSSLMODE')
function Write-Result {param([string]$State,[string]$Message) Write-Output ("{0}|{1}" -f $State,$Message)}
function Assert-RouteFlagDisabled {foreach($scope in @('Process','User','Machine')){if([Environment]::GetEnvironmentVariable('DERALEDGER_ADMIN_READINESS_ROUTES_ENABLED',$scope) -eq 'true'){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_ROUTE_FLAG_MUST_REMAIN_DISABLED'}}}
function Assert-PlainConnectionFields {param([string]$Value)if([string]::IsNullOrWhiteSpace($Value) -or $Value -match '(?i)://|(?:^|\s)(?:host|port|dbname|user|password)\s*='){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_CONNECTION_STRING_REJECTED'}}
function Read-LocalTarget {$DbHost=(Read-Host 'Local database host (localhost or 127.0.0.1 only)').Trim().ToLowerInvariant();$DbPort=(Read-Host 'Local database port (default 5432)').Trim();$DbName=(Read-Host 'Disposable local database name').Trim().ToLowerInvariant();$DbUser=(Read-Host 'Local database user').Trim();if([string]::IsNullOrWhiteSpace($DbPort)){$DbPort='5432'};foreach($value in @($DbHost,$DbPort,$DbName,$DbUser)){Assert-PlainConnectionFields $value};if($DbHost -match '(?i)supabase\.(?:co|com)'){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_SUPABASE_CLOUD_HOST_REJECTED'};if($DbHost -notin @('localhost','127.0.0.1')){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_NONLOCAL_HOST_REJECTED'};if($DbPort -notmatch '^[0-9]{1,5}$' -or [int]$DbPort -lt 1 -or [int]$DbPort -gt 65535){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_PORT_REJECTED'};if($DbName -match '(?i)(?:production|prod|staging|preview|main|^postgres$)'){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_DATABASE_NAME_REJECTED'};if($DbName -notmatch '(?i)(local|test|rehearsal|disposable|admin_readiness)'){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_DISPOSABLE_DATABASE_NAME_REQUIRED'};[pscustomobject]@{DbHost=$DbHost;DbPort=$DbPort;DbName=$DbName;DbUser=$DbUser}}
function Assert-ServiceRolePrerequisiteEvidence {param($Target)$EvidenceFile=Get-ChildItem -LiteralPath $EvidenceRoot -Filter 'preflight-*.txt' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;if($null -eq $EvidenceFile){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_SERVICE_ROLE_EVIDENCE_MISSING'};$Evidence=Get-Content -LiteralPath $EvidenceFile.FullName;if($Evidence -notcontains ("connected_database={0}" -f $Target.DbName)){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_PREFLIGHT_TARGET_EVIDENCE_MISMATCH'};foreach($line in @('READ_ONLY_METADATA=PASS','SERVICE_ROLE_EXISTS=PASS','SERVICE_ROLE_BYPASSRLS=PASS','SERVICE_ROLE_ASSUMABLE=PASS')){if($Evidence -notcontains $line){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_SERVICE_ROLE_PREREQUISITE_FAILED'}}}
function Invoke-BehaviorSql {param($Target,[string]$Psql,[string]$Sql)$SavedPgEnvironment=@{};foreach($environmentName in $PostgresEnvironmentNames){$SavedPgEnvironment[$environmentName]=[Environment]::GetEnvironmentVariable($environmentName,'Process');[Environment]::SetEnvironmentVariable($environmentName,$null,'Process')};$SecurePassword=Read-Host 'Local database password (not stored or echoed)' -AsSecureString;$PasswordBstr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword);$PlainPassword=$null;try{$PlainPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($PasswordBstr);[Environment]::SetEnvironmentVariable('PGPASSWORD',$PlainPassword,'Process');$output=& $Psql -X -v ON_ERROR_STOP=1 -h $Target.DbHost -p $Target.DbPort -U $Target.DbUser -d $Target.DbName -At -c $Sql 2>$null;if($LASTEXITCODE -ne 0){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_BEHAVIOR_FAILED'};return @($output)}finally{if($null -ne $PasswordBstr){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($PasswordBstr)};$PlainPassword=$null;foreach($environmentName in $PostgresEnvironmentNames){[Environment]::SetEnvironmentVariable($environmentName,$SavedPgEnvironment[$environmentName],'Process')}}}

try {
  Assert-RouteFlagDisabled;$Psql=(Get-Command $PsqlPath -ErrorAction Stop).Source;$Target=Read-LocalTarget;Assert-ServiceRolePrerequisiteEvidence -Target $Target
  $BehaviorSql=@'
BEGIN;
SET LOCAL ROLE service_role;
CREATE TEMP TABLE pg_temp.admin_readiness_behavior_results (name text primary key, passed boolean not null);
WITH created AS (SELECT result_code FROM public.create_admin_readiness_csrf_token_v1(repeat('a',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_create_success',result_code='created' FROM created;
WITH collided AS (SELECT result_code FROM public.create_admin_readiness_csrf_token_v1(repeat('a',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_create_collision_conflict',result_code='conflict' FROM collided;
WITH read_ok AS (SELECT result_code,session_binding_digest FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64))) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_read_allow',result_code='found' AND session_binding_digest=repeat('b',64) FROM read_ok;
INSERT INTO public.admin_readiness_csrf_tokens(token_digest,session_binding_digest,operation,method,created_at,expires_at) VALUES(repeat('c',64),repeat('d',64),'readiness_issue','POST',now()-interval '2 minutes',now()-interval '1 minute');
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_expired_denied',result_code='expired' FROM public.read_admin_readiness_csrf_token_v1(repeat('c',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_session_mismatch_denied',session_binding_digest<>repeat('e',64) FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64));
WITH rotation AS (SELECT result_code FROM public.rotate_admin_readiness_csrf_token_v1(repeat('a',64),repeat('f',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_rotate_success',result_code='rotated' FROM rotation;
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_predecessor_invalidated',result_code='missing' FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_replacement_allowed',result_code='found' FROM public.read_admin_readiness_csrf_token_v1(repeat('f',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_invalidate_binding_bounded',result_code='invalidated' AND deleted_count BETWEEN 1 AND 4 FROM public.invalidate_admin_readiness_csrf_binding_v1(repeat('b',64),4);
WITH first_decision AS (SELECT result_code FROM public.decide_admin_readiness_throttle_v1('admin_readiness_local_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3)) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'throttle_allow',result_code='allow' FROM first_decision;
SELECT result_code INTO TEMP TABLE pg_temp.throttle_two FROM public.decide_admin_readiness_throttle_v1('admin_readiness_local_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3);
SELECT result_code INTO TEMP TABLE pg_temp.throttle_three FROM public.decide_admin_readiness_throttle_v1('admin_readiness_local_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3);
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'throttle_rate_limited',result_code='rate_limited' FROM pg_temp.throttle_three;
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'malformed_bounds_denied',result_code='invalid' FROM public.decide_admin_readiness_throttle_v1('invalid_namespace','bad',repeat('z',64),now(),now(),0);
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'cleanup_expired_rows',result_code IN ('cleaned','nothing_to_clean') FROM public.cleanup_admin_readiness_security_storage_v1(10);
SELECT 'behavior=' || name || '=' || CASE WHEN passed THEN 'PASS' ELSE 'FAIL' END FROM pg_temp.admin_readiness_behavior_results ORDER BY name;
ROLLBACK;
'@
  $Output=Invoke-BehaviorSql -Target $Target -Psql $Psql -Sql $BehaviorSql;if($Output -match '=FAIL$'){throw 'ADMIN_READINESS_LOCAL_REHEARSAL_BEHAVIOR_ASSERTION_FAILED'}
  New-Item -ItemType Directory -Path $EvidenceRoot -Force|Out-Null;$EvidencePath=Join-Path $EvidenceRoot ("behavior-{0}.txt" -f [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss'));[System.IO.File]::WriteAllLines($EvidencePath,@('BEHAVIOR=PASS','TARGET=LOCAL_DISPOSABLE','NAMESPACE=admin_readiness_local_v1','TRANSACTION=ROLLED_BACK','RAW_DIAGNOSTICS=NOT_RECORDED','ROUTE_FLAG=DISABLED'),[System.Text.UTF8Encoding]::new($false))
  Write-Result 'PASS' 'csrf_and_throttle_behavior_verified_in_rolled_back_transaction';Write-Result 'PASS' 'behavior_complete'
} catch {Write-Result 'FAIL' $_.Exception.Message;exit 1}
