[CmdletBinding()]
param([string]$PsqlPath = 'psql')

Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$ProjectRoot=Split-Path -Parent $PSScriptRoot
$EvidenceRoot=Join-Path $ProjectRoot 'local-evidence/admin-readiness-security/staging'
$PostgresEnvironmentNames=@('PGHOST','PGHOSTADDR','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS','PGSSLMODE')
$ApprovedStagingProjectRef='fsjljliiyfchkwbjifzw'
$ApprovedStagingPoolerHost='aws-1-eu-central-2.pooler.supabase.com'
$ApprovedStagingPort='5432'
$ApprovedStagingDatabase='postgres'
$ApprovedStagingUser='postgres.fsjljliiyfchkwbjifzw'
function Write-Result {param([string]$State,[string]$Message)Write-Output("{0}|{1}" -f $State,$Message)}
function Assert-RouteFlagDisabled {foreach($scope in @('Process','User','Machine')){if([Environment]::GetEnvironmentVariable('DERALEDGER_ADMIN_READINESS_ROUTES_ENABLED',$scope) -eq 'true'){throw 'ADMIN_READINESS_STAGING_ROUTE_FLAG_MUST_REMAIN_DISABLED'}}}
function Assert-PlainConnectionField {param([string]$Value)if([string]::IsNullOrWhiteSpace($Value) -or $Value -match '(?i)://|(?:^|\s)(?:host|port|dbname|user|password)\s*='){throw 'ADMIN_READINESS_STAGING_CONNECTION_STRING_REJECTED'}}
function Get-Sha256Hex {param([string]$Value)$Sha256=[System.Security.Cryptography.SHA256]::Create();try{return ([System.BitConverter]::ToString($Sha256.ComputeHash([System.Text.Encoding]::UTF8.GetBytes($Value)))).Replace('-','').ToLowerInvariant()}finally{if($null -ne $Sha256){$Sha256.Dispose()}}}
function Read-StagingTarget {$DbHost=(Read-Host 'Exact reviewed staging Supabase pooler host').Trim().ToLowerInvariant();$DbPort=(Read-Host 'Staging pooler port (default 5432)').Trim();$DbName=(Read-Host 'Staging database name').Trim().ToLowerInvariant();$DbUser=(Read-Host 'Staging pooler database user').Trim().ToLowerInvariant();$ConfirmedStagingProjectRef=(Read-Host 'Confirm the reviewed staging Supabase project ref').Trim().ToLowerInvariant();if([string]::IsNullOrWhiteSpace($DbPort)){$DbPort='5432'};foreach($value in @($DbHost,$DbPort,$DbName,$DbUser,$ConfirmedStagingProjectRef)){Assert-PlainConnectionField $value};if($DbHost -in @('localhost','127.0.0.1','::1')){throw 'ADMIN_READINESS_STAGING_LOCALHOST_REJECTED'};if($DbHost -notmatch '^[a-z0-9-]+\.pooler\.supabase\.com$'){throw 'ADMIN_READINESS_STAGING_UNRECOGNIZED_HOST_REJECTED'};$UserMatch=[regex]::Match($DbUser,'^postgres\.([a-z0-9]+)$');if(-not $UserMatch.Success){throw 'ADMIN_READINESS_STAGING_UNRECOGNIZED_USER_REJECTED'};$ParsedStagingProjectRef=$UserMatch.Groups[1].Value;if($ApprovedStagingUser -cne "postgres.$ApprovedStagingProjectRef"){throw 'ADMIN_READINESS_STAGING_APPROVED_IDENTITY_MANIFEST_INVALID'};if($DbHost -cne $ApprovedStagingPoolerHost){throw 'ADMIN_READINESS_STAGING_POOLER_HOST_NOT_APPROVED'};if($DbPort -cne $ApprovedStagingPort){throw 'ADMIN_READINESS_STAGING_PORT_NOT_APPROVED'};if($DbName -cne $ApprovedStagingDatabase){throw 'ADMIN_READINESS_STAGING_DATABASE_NOT_APPROVED'};if($DbUser -cne $ApprovedStagingUser){throw 'ADMIN_READINESS_STAGING_USER_NOT_APPROVED'};if($ParsedStagingProjectRef -cne $ApprovedStagingProjectRef){throw 'ADMIN_READINESS_STAGING_PROJECT_REF_NOT_APPROVED'};if($ConfirmedStagingProjectRef -cne $ApprovedStagingProjectRef){throw 'ADMIN_READINESS_STAGING_PROJECT_REF_CONFIRMATION_MISMATCH'};if($DbHost -match '(?i)(prod|production|live)' -or $DbName -match '(?i)(prod|production|live)' -or $DbUser -match '(?i)(prod|production|live)'){throw 'ADMIN_READINESS_STAGING_PRODUCTION_INDICATOR_REJECTED'};if($DbPort -notmatch '^[0-9]{1,5}$' -or [int]$DbPort -lt 1 -or [int]$DbPort -gt 65535){throw 'ADMIN_READINESS_STAGING_PORT_REJECTED'};[pscustomobject]@{DbHost=$DbHost;DbPort=$DbPort;DbName=$DbName;DbUser=$DbUser;ApprovedStagingProjectRef=$ApprovedStagingProjectRef;ApprovedStagingPoolerHost=$ApprovedStagingPoolerHost;TargetFingerprint=(Get-Sha256Hex "$DbHost|$DbPort|$DbName|$DbUser|$ApprovedStagingProjectRef")}}
function Assert-MatchingPostflightEvidence {param($Target)$EvidenceFile=Get-ChildItem -LiteralPath $EvidenceRoot -Filter 'postflight-*.txt' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;if($null -eq $EvidenceFile){throw 'ADMIN_READINESS_STAGING_POSTFLIGHT_EVIDENCE_MISSING'};$Evidence=Get-Content -LiteralPath $EvidenceFile.FullName;foreach($line in @('POSTFLIGHT=PASS',("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint),'EXACT_RPC_SIGNATURES=PASS','RLS=PASS','SERVICE_ROLE_ONLY=PASS','SECURITY_INVOKER=PASS','SEARCH_PATH=PASS','BUSINESS_SCHEMA_BASELINE=PASS','ROUTE_FLAG=DISABLED')){if($Evidence -notcontains $line){throw 'ADMIN_READINESS_STAGING_POSTFLIGHT_TARGET_EVIDENCE_MISMATCH'}};$Preflight=Get-ChildItem -LiteralPath $EvidenceRoot -Filter 'preflight-*.txt' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;if($null -eq $Preflight){throw 'ADMIN_READINESS_STAGING_SERVICE_ROLE_EVIDENCE_MISSING'};$PreflightEvidence=Get-Content -LiteralPath $Preflight.FullName;foreach($line in @('PREFLIGHT=PASS',("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint),'SERVICE_ROLE=PASS','SERVICE_ROLE_BYPASSRLS=PASS','SERVICE_ROLE_ASSUMABLE=PASS')){if($PreflightEvidence -notcontains $line){throw 'ADMIN_READINESS_STAGING_SERVICE_ROLE_PREREQUISITE_FAILED'}}}
function Invoke-BehaviorPsql {param($Target,[string]$Psql,[string]$Sql)$SavedPgEnvironment=@{};foreach($environmentName in $PostgresEnvironmentNames){$SavedPgEnvironment[$environmentName]=[Environment]::GetEnvironmentVariable($environmentName,'Process');[Environment]::SetEnvironmentVariable($environmentName,$null,'Process')};$SecurePassword=Read-Host 'Staging database password (entered locally; not stored or echoed)' -AsSecureString;$PasswordBstr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword);$PlainPassword=$null;try{$PlainPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($PasswordBstr);[Environment]::SetEnvironmentVariable('PGPASSWORD',$PlainPassword,'Process');[Environment]::SetEnvironmentVariable('PGSSLMODE','require','Process');$output=& $Psql -X -v ON_ERROR_STOP=1 -h $Target.DbHost -p $Target.DbPort -U $Target.DbUser -d $Target.DbName -At -c $Sql 2>$null;if($LASTEXITCODE -ne 0){throw 'ADMIN_READINESS_STAGING_BEHAVIOR_FAILED'};return @($output)}finally{if($null -ne $PasswordBstr){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($PasswordBstr)};$PlainPassword=$null;foreach($environmentName in $PostgresEnvironmentNames){[Environment]::SetEnvironmentVariable($environmentName,$SavedPgEnvironment[$environmentName],'Process')}}}
try {
  Assert-RouteFlagDisabled;$Psql=(Get-Command $PsqlPath -ErrorAction Stop).Source;$Target=Read-StagingTarget;Assert-MatchingPostflightEvidence -Target $Target;$Confirmation=(Read-Host 'Type exact confirmation before staging behavior checks').Trim();if($Confirmation -cne 'STAGING RUN ADMIN READINESS SECURITY BEHAVIOR CHECKS'){throw 'ADMIN_READINESS_STAGING_BEHAVIOR_CONFIRMATION_REQUIRED'}
  $BehaviorSql=@'
BEGIN;
SET LOCAL ROLE service_role;
CREATE TEMP TABLE pg_temp.admin_readiness_behavior_results (name text primary key, passed boolean not null);
WITH created AS (SELECT result_code FROM public.create_admin_readiness_csrf_token_v1(repeat('a',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_create_success',result_code='created' FROM created;
WITH collided AS (SELECT result_code FROM public.create_admin_readiness_csrf_token_v1(repeat('a',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_create_collision_conflict',result_code='conflict' FROM collided;
WITH read_ok AS (SELECT result_code,session_binding_digest FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64))) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_read_allow',result_code='found' AND session_binding_digest=repeat('b',64) FROM read_ok;
INSERT INTO public.admin_readiness_csrf_tokens(token_digest,session_binding_digest,operation,method,created_at,expires_at) VALUES(repeat('c',64),repeat('d',64),'readiness_issue','POST',now()-interval '2 minutes',now()-interval '1 minute');
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_expired_denied',result_code='expired' FROM public.read_admin_readiness_csrf_token_v1(repeat('c',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_session_mismatch_denied',session_binding_digest<>repeat('e',64) FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64));
WITH rotation AS (SELECT result_code FROM public.rotate_admin_readiness_csrf_token_v1(repeat('a',64),repeat('f',64),repeat('b',64),'readiness_issue','POST',now()+interval '10 minutes')) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_rotate_success',result_code='rotated' FROM rotation;
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_predecessor_invalidated',result_code='missing' FROM public.read_admin_readiness_csrf_token_v1(repeat('a',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_replacement_allowed',result_code='found' FROM public.read_admin_readiness_csrf_token_v1(repeat('f',64));
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'csrf_invalidate_binding_bounded',result_code='invalidated' AND deleted_count BETWEEN 1 AND 4 FROM public.invalidate_admin_readiness_csrf_binding_v1(repeat('b',64),4);
WITH first_decision AS (SELECT result_code FROM public.decide_admin_readiness_throttle_v1('admin_readiness_staging_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3)) INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'throttle_allow',result_code='allow' FROM first_decision;
SELECT result_code INTO TEMP TABLE pg_temp.throttle_two FROM public.decide_admin_readiness_throttle_v1('admin_readiness_staging_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3);
SELECT result_code INTO TEMP TABLE pg_temp.throttle_three FROM public.decide_admin_readiness_throttle_v1('admin_readiness_staging_v1','readiness_issue',repeat('1',64),date_trunc('minute',now()),date_trunc('minute',now())+interval '60 seconds',3);
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'throttle_rate_limited',result_code='rate_limited' FROM pg_temp.throttle_three;
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'malformed_bounds_denied',result_code='invalid' FROM public.decide_admin_readiness_throttle_v1('invalid_namespace','bad',repeat('z',64),now(),now(),0);
INSERT INTO pg_temp.admin_readiness_behavior_results SELECT 'cleanup_expired_rows',result_code IN ('cleaned','nothing_to_clean') FROM public.cleanup_admin_readiness_security_storage_v1(10);
SELECT 'behavior=' || name || '=' || CASE WHEN passed THEN 'PASS' ELSE 'FAIL' END FROM pg_temp.admin_readiness_behavior_results ORDER BY name;
ROLLBACK;
'@
  $Output=Invoke-BehaviorPsql -Target $Target -Psql $Psql -Sql $BehaviorSql;$ExpectedBehaviorResults=@('csrf_create_success','csrf_create_collision_conflict','csrf_read_allow','csrf_expired_denied','csrf_session_mismatch_denied','csrf_rotate_success','csrf_predecessor_invalidated','csrf_replacement_allowed','csrf_invalidate_binding_bounded','throttle_allow','throttle_rate_limited','cleanup_expired_rows','malformed_bounds_denied');foreach($result in $ExpectedBehaviorResults){if($Output -notcontains ("behavior={0}=PASS" -f $result)){throw 'ADMIN_READINESS_STAGING_BEHAVIOR_ASSERTION_FAILED'}}
  New-Item -ItemType Directory -Path $EvidenceRoot -Force|Out-Null;$EvidencePath=Join-Path $EvidenceRoot ("behavior-{0}.txt" -f [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss'));[System.IO.File]::WriteAllLines($EvidencePath,@('BEHAVIOR=PASS','TARGET=STAGING',("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint),'NAMESPACE=admin_readiness_staging_v1','TRANSACTION=ROLLED_BACK','RAW_DIAGNOSTICS=NOT_RECORDED','ROUTE_FLAG=DISABLED'),[System.Text.UTF8Encoding]::new($false));Write-Result 'PASS' 'csrf_and_throttle_behavior_verified_in_rolled_back_transaction';Write-Result 'PASS' 'behavior_complete'
} catch {Write-Result 'FAIL' $_.Exception.Message;exit 1}
