[CmdletBinding()]
param([string]$PsqlPath = 'psql')

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProjectRoot=Split-Path -Parent $PSScriptRoot
$EvidenceRoot=Join-Path $ProjectRoot 'local-evidence/admin-readiness-security/staging'
$PostgresEnvironmentNames=@('PGHOST','PGHOSTADDR','PGPORT','PGDATABASE','PGUSER','PGPASSWORD','PGSERVICE','PGSERVICEFILE','PGPASSFILE','PGOPTIONS','PGSSLMODE')
$ApprovedStagingProjectRef='fsjljliiyfchkwbjifzw'
$ApprovedStagingDbHost='db.fsjljliiyfchkwbjifzw.supabase.co'
function Write-Result {param([string]$State,[string]$Message)Write-Output("{0}|{1}" -f $State,$Message)}
function Assert-RouteFlagDisabled {foreach($scope in @('Process','User','Machine')){if([Environment]::GetEnvironmentVariable('DERALEDGER_ADMIN_READINESS_ROUTES_ENABLED',$scope) -eq 'true'){throw 'ADMIN_READINESS_STAGING_ROUTE_FLAG_MUST_REMAIN_DISABLED'}}}
function Assert-PlainConnectionField {param([string]$Value)if([string]::IsNullOrWhiteSpace($Value) -or $Value -match '(?i)://|(?:^|\s)(?:host|port|dbname|user|password)\s*='){throw 'ADMIN_READINESS_STAGING_CONNECTION_STRING_REJECTED'}}
function Get-Sha256Hex {param([string]$Value)return ([Convert]::ToHexString([Security.Cryptography.SHA256]::HashData([Text.Encoding]::UTF8.GetBytes($Value)))).ToLowerInvariant()}
function Read-StagingTarget {$DbHost=(Read-Host 'Exact reviewed staging Supabase database host').Trim().ToLowerInvariant();$DbPort=(Read-Host 'Staging database port (default 5432)').Trim();$DbName=(Read-Host 'Staging database name').Trim().ToLowerInvariant();$DbUser=(Read-Host 'Staging database user').Trim();$ConfirmedStagingProjectRef=(Read-Host 'Confirm the reviewed staging Supabase project ref').Trim().ToLowerInvariant();if([string]::IsNullOrWhiteSpace($DbPort)){$DbPort='5432'};foreach($value in @($DbHost,$DbPort,$DbName,$DbUser,$ConfirmedStagingProjectRef)){Assert-PlainConnectionField $value};if($DbHost -in @('localhost','127.0.0.1','::1')){throw 'ADMIN_READINESS_STAGING_LOCALHOST_REJECTED'};$HostMatch=[regex]::Match($DbHost,'^db\.([a-z0-9-]+)\.supabase\.co$');if(-not $HostMatch.Success){throw 'ADMIN_READINESS_STAGING_UNRECOGNIZED_HOST_REJECTED'};$ParsedStagingProjectRef=$HostMatch.Groups[1].Value;if($ApprovedStagingDbHost -cne "db.$ApprovedStagingProjectRef.supabase.co"){throw 'ADMIN_READINESS_STAGING_APPROVED_IDENTITY_MANIFEST_INVALID'};if($DbHost -cne $ApprovedStagingDbHost){throw 'ADMIN_READINESS_STAGING_HOST_NOT_APPROVED'};if($ParsedStagingProjectRef -cne $ApprovedStagingProjectRef){throw 'ADMIN_READINESS_STAGING_PROJECT_REF_NOT_APPROVED'};if($ConfirmedStagingProjectRef -cne $ApprovedStagingProjectRef){throw 'ADMIN_READINESS_STAGING_PROJECT_REF_CONFIRMATION_MISMATCH'};if($DbHost -match '(?i)(prod|production|live)' -or $DbName -match '(?i)(prod|production|live)' -or $DbUser -match '(?i)(prod|production|live)'){throw 'ADMIN_READINESS_STAGING_PRODUCTION_INDICATOR_REJECTED'};if($DbPort -notmatch '^[0-9]{1,5}$' -or [int]$DbPort -lt 1 -or [int]$DbPort -gt 65535){throw 'ADMIN_READINESS_STAGING_PORT_REJECTED'};[pscustomobject]@{DbHost=$DbHost;DbPort=$DbPort;DbName=$DbName;DbUser=$DbUser;ApprovedStagingProjectRef=$ApprovedStagingProjectRef;ApprovedStagingDbHost=$ApprovedStagingDbHost;TargetFingerprint=(Get-Sha256Hex "$DbHost|$DbPort|$DbName|$DbUser|$ApprovedStagingProjectRef")}}
function Assert-MatchingApplyEvidence {param($Target)$EvidenceFile=Get-ChildItem -LiteralPath $EvidenceRoot -Filter 'apply-*.txt' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;if($null -eq $EvidenceFile){throw 'ADMIN_READINESS_STAGING_APPLY_EVIDENCE_MISSING'};$Evidence=Get-Content -LiteralPath $EvidenceFile.FullName;foreach($line in @('APPLY=PASS','TARGET=STAGING',("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint),'ROUTE_FLAG=DISABLED','RUNTIME_ADOPTION=NO')){if($Evidence -notcontains $line){throw 'ADMIN_READINESS_STAGING_APPLY_TARGET_EVIDENCE_MISMATCH'}}}
function Get-PreflightBaseline {param($Target)$EvidenceFile=Get-ChildItem -LiteralPath $EvidenceRoot -Filter 'preflight-*.txt' -File -ErrorAction SilentlyContinue|Sort-Object LastWriteTimeUtc -Descending|Select-Object -First 1;if($null -eq $EvidenceFile){throw 'ADMIN_READINESS_STAGING_PREFLIGHT_EVIDENCE_MISSING'};$Evidence=Get-Content -LiteralPath $EvidenceFile.FullName;if($Evidence -notcontains ("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint)){throw 'ADMIN_READINESS_STAGING_PREFLIGHT_TARGET_EVIDENCE_MISMATCH'};$Baseline=@($Evidence|Where-Object{$_ -match '^business_schema_baseline=[0-9a-f]{32}$'})[0];if([string]::IsNullOrWhiteSpace($Baseline)){throw 'ADMIN_READINESS_STAGING_BASELINE_EVIDENCE_MISSING'};return $Baseline}
function Invoke-StagingPsql {param($Target,[string]$Psql,[string]$Sql)$SavedPgEnvironment=@{};foreach($environmentName in $PostgresEnvironmentNames){$SavedPgEnvironment[$environmentName]=[Environment]::GetEnvironmentVariable($environmentName,'Process');[Environment]::SetEnvironmentVariable($environmentName,$null,'Process')};$SecurePassword=Read-Host 'Staging database password (entered locally; not stored or echoed)' -AsSecureString;$PasswordBstr=[Runtime.InteropServices.Marshal]::SecureStringToBSTR($SecurePassword);$PlainPassword=$null;try{$PlainPassword=[Runtime.InteropServices.Marshal]::PtrToStringBSTR($PasswordBstr);[Environment]::SetEnvironmentVariable('PGPASSWORD',$PlainPassword,'Process');$output=& $Psql -X -v ON_ERROR_STOP=1 -h $Target.DbHost -p $Target.DbPort -U $Target.DbUser -d $Target.DbName -At -c $Sql 2>$null;if($LASTEXITCODE -ne 0){throw 'ADMIN_READINESS_STAGING_POSTFLIGHT_QUERY_FAILED'};return @($output)}finally{if($null -ne $PasswordBstr){[Runtime.InteropServices.Marshal]::ZeroFreeBSTR($PasswordBstr)};$PlainPassword=$null;foreach($environmentName in $PostgresEnvironmentNames){[Environment]::SetEnvironmentVariable($environmentName,$SavedPgEnvironment[$environmentName],'Process')}}}
try {
  Assert-RouteFlagDisabled;$Psql=(Get-Command $PsqlPath -ErrorAction Stop).Source;$Target=Read-StagingTarget;Assert-MatchingApplyEvidence -Target $Target;$ExpectedBaseline=Get-PreflightBaseline -Target $Target
  $CheckSql=@'
WITH expected(identity) AS (VALUES
 ('public.create_admin_readiness_csrf_token_v1(text,text,text,text,timestamp with time zone)'),
 ('public.read_admin_readiness_csrf_token_v1(text)'),
 ('public.rotate_admin_readiness_csrf_token_v1(text,text,text,text,text,timestamp with time zone)'),
 ('public.invalidate_admin_readiness_csrf_binding_v1(text,integer)'),
 ('public.decide_admin_readiness_throttle_v1(text,text,text,timestamp with time zone,timestamp with time zone,integer)'),
 ('public.cleanup_admin_readiness_security_storage_v1(integer)'))
SELECT 'exact_rpc_signatures=' || count(*) FROM expected WHERE to_regprocedure(identity) IS NOT NULL;
SELECT 'approved_rpc_overloads=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1');
SELECT 'unexpected_security_functions=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname LIKE '%admin_readiness%' AND p.proname NOT IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1');
SELECT 'tables=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r' AND c.relname IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows');
SELECT 'unexpected_security_tables=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind='r' AND c.relname LIKE 'admin_readiness_%' AND c.relname NOT IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows');
SELECT 'rls=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows') AND c.relrowsecurity;
SELECT 'browser_policies=' || count(*) FROM pg_policies WHERE schemaname='public' AND tablename IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows');
SELECT 'browser_table_grants=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows') AND (has_table_privilege('anon',c.oid,'SELECT,INSERT,UPDATE,DELETE') OR has_table_privilege('authenticated',c.oid,'SELECT,INSERT,UPDATE,DELETE'));
SELECT 'service_role_table_grants=' || count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows') AND has_table_privilege('service_role',c.oid,'SELECT,INSERT,UPDATE,DELETE');
SELECT 'service_role_function_grants=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1') AND has_function_privilege('service_role',p.oid,'EXECUTE');
SELECT 'browser_function_grants=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1') AND (has_function_privilege('anon',p.oid,'EXECUTE') OR has_function_privilege('authenticated',p.oid,'EXECUTE'));
SELECT 'security_invoker=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1') AND NOT p.prosecdef;
SELECT 'hardened_search_path=' || count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('create_admin_readiness_csrf_token_v1','read_admin_readiness_csrf_token_v1','rotate_admin_readiness_csrf_token_v1','invalidate_admin_readiness_csrf_binding_v1','decide_admin_readiness_throttle_v1','cleanup_admin_readiness_security_storage_v1') AND coalesce(array_to_string(p.proconfig,','),'') LIKE '%search_path=pg_catalog, public%';
SELECT 'unsafe_columns=' || count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows') AND column_name IN ('raw_token','jwt','cookie','header','user_metadata','email','user_id');
SELECT 'table_bytes=' || coalesce(sum(pg_total_relation_size(c.oid)),0) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relname IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows');
SELECT 'business_schema_baseline=' || md5(coalesce(string_agg(c.relname || ':' || c.relfilenode || ':' || c.relnatts, ',' ORDER BY c.relname), 'empty')) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') AND c.relname NOT IN ('admin_readiness_csrf_tokens','admin_readiness_csrf_binding_index','admin_readiness_throttle_windows');
'@
  $Output=Invoke-StagingPsql -Target $Target -Psql $Psql -Sql $CheckSql;$Required=@('exact_rpc_signatures=6','approved_rpc_overloads=6','unexpected_security_functions=0','tables=3','unexpected_security_tables=0','rls=3','browser_policies=0','browser_table_grants=0','service_role_table_grants=3','service_role_function_grants=6','browser_function_grants=0','security_invoker=6','hardened_search_path=6','unsafe_columns=0');foreach($required in $Required){if($Output -notcontains $required){throw "ADMIN_READINESS_STAGING_POSTFLIGHT_FAILED:$required"}};$ActualBaseline=@($Output|Where-Object{$_ -match '^business_schema_baseline=[0-9a-f]{32}$'})[0];if($ExpectedBaseline -ne $ActualBaseline){throw 'ADMIN_READINESS_STAGING_BUSINESS_SCHEMA_BASELINE_MISMATCH'}
  New-Item -ItemType Directory -Path $EvidenceRoot -Force|Out-Null;$EvidencePath=Join-Path $EvidenceRoot ("postflight-{0}.txt" -f [DateTime]::UtcNow.ToString('yyyyMMdd-HHmmss'));[System.IO.File]::WriteAllLines($EvidencePath,@('POSTFLIGHT=PASS','TARGET=STAGING',("TARGET_FINGERPRINT={0}" -f $Target.TargetFingerprint),'EXACT_RPC_SIGNATURES=PASS','RPC_OVERLOADS=REJECTED','RLS=PASS','SERVICE_ROLE_ONLY=PASS','SECURITY_INVOKER=PASS','SEARCH_PATH=PASS','BUSINESS_SCHEMA_BASELINE=PASS','FREE_TIER_TABLE_SIZE_CHECK=COMPLETE','ROUTE_FLAG=DISABLED'),[System.Text.UTF8Encoding]::new($false));Write-Result 'PASS' 'approved_objects_and_security_manifest_verified';Write-Result 'PASS' 'postflight_complete'
} catch {Write-Result 'FAIL' $_.Exception.Message;exit 1}
